[project]
name = "readme-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-genai>=2.26.0",
    "python-dotenv>=1.2.4",
]

[project.scripts]
readme-agent = "readme_agent:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
